{
 "title": "Queue Status",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "qmgr", "label": "Queue Manager", "query": "label_values(qmgr)" }
  ]
 },
 "panels": [
  {
   "title": "Message Lifetime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "ibmmq_queue_qtime_short",
     "legendFormat": "QTime Short: {{queue}}@{{qmgr}}"
    },
    { "expr": "ibmmq_queue_qtime_long", "legendFormat": "QTime Long: {{queue}}@{{qmgr}}" }
   ]
  },
  {
   "title": "Oldest message",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "ibmmq_queue_oldest_message_age", "legendFormat": "Oldest msg: {{queue}}@{{qmgr}}" },
    {
     "expr": "max(ibmmq_queue_oldest_message_age)",
     "legendFormat": "Maximum"
    }
   ]
  },
  {
   "title": "Put/Get Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "ibmmq_queue_time_since_get", "legendFormat": "Since Get: {{queue}}@{{qmgr}}" },
    { "expr": "ibmmq_queue_time_since_put", "legendFormat": "Since Get: {{queue}}@{{qmgr}}" }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ibmmq_queue_depth", "legendFormat": "Depth: {{queue}}@{{qmgr}}" },
    {
     "expr": "(ibmmq_queue_depth * 100 )/ ibmmq_queue_attribute_max_depth",
     "legendFormat": "% Depth: {{queue}}@{{qmgr}}"
    }
   ]
  },
  {
   "title": "QFile Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * ibmmq_queue_qfile_current_size/ibmmq_queue_qfile_max_size",
     "legendFormat": "Queue: {{queue}}  QMgr: {{ qmgr}}"
    }
   ]
  },
  {
   "title": "Object handles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ibmmq_queue_input_handles{queue=\"$queue\"}",
     "legendFormat": "IPPROCS: {{queue}}@{{qmgr}}"
    },
    {
     "expr": "ibmmq_queue_output_handles{queue=\"$queue\"}",
     "legendFormat": "OPPROCS: {{queue}}@{{qmgr}}"
    }
   ]
  }
 ]
}