apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: quickstart-mq-extended-metrics
spec:
  endpoints:
    - bearerTokenSecret:
        key: ''
      port: metrics
      scheme: http
  namespaceSelector:
    matchNames:
      - vish-cp4i-ui
  selector:
    matchLabels:
      app: mq-extended-metrics
