apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: nativeha
  namespace: cp4i
  finalizers:
    - finalizer.queuemanagers.mq.ibm.com
spec:
  license:
    accept: true
    license: L-RJON-C7QG3S
    metric: VirtualProcessorCore
    use: NonProduction
  tracing:
    agent: {}
    collector: {}
    enabled: false
    namespace: ''
  terminationGracePeriodSeconds: 30
  pki:
    keys:
      - name: default
        secret:
          items:
            - tls.key
            - tls.crt
          secretName: nativehacert
  securityContext:
    initVolumeAsRoot: false
  web:
    enabled: true
  version: 9.2.5.0-r3
  telemetry:
    tracing:
      instana:
        enabled: false
        protocol: http
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
          resources: {}
  queueManager:
    metrics:
      enabled: true
    ini:
      - configMap:
          items:
            - nativeha.ini
          name: nativeha-qm-ini
    resources:
      limits:
        cpu: '2'
        memory: 2Gi
      requests:
        cpu: '1'
        memory: 1Gi
    readinessProbe:
      failureThreshold: 1
      initialDelaySeconds: 0
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3
    route:
      enabled: true
    name: NATIVEHA
    livenessProbe:
      failureThreshold: 1
      initialDelaySeconds: 0
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    imagePullPolicy: IfNotPresent
    debug: false
    startupProbe:
      failureThreshold: 24
      initialDelaySeconds: 0
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
    mqsc:
      - configMap:
          items:
            - nativeha.mqsc
          name: nativehamqsc
    logFormat: Basic
    availability:
      type: NativeHA
      updateStrategy: RollingUpdate
    storage:
      defaultClass: gp2-csi
      persistedData:
        enabled: true
        size: 10Gi
        type: persistent-claim
      queueManager:
        size: 10Gi
        type: persistent-claim
      recoveryLogs:
        enabled: true
        size: 10Gi
        type: persistent-claim