apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-cwagentconfig
  namespace: amazon-cloudwatch
data:
  cwagentconfig.json: |
    {
      "agent": { 
        "region": "ca-central-1"
       },
      "logs": {
        "metrics_collected": {
          "prometheus": {
            "cluster_name": "cp4i",
            "log_group_name": "/aws/containerinsights/cp4i/prometheus",
            "prometheus_config_path": "/etc/prometheusconfig/prometheus.yaml",
            "emf_processor": {
              "metric_declaration": [
                
                {"source_labels": ["job","code"],
                 "label_matcher": "^kubernetes-apiservers;2[0-9]{2}$",
                 "dimensions": [["ClusterName","Service","code"]],
                 "metric_selectors": [
                   "^apiserver_request_total$"
                  ]
                },
               {"source_labels": ["job"],
                "label_matcher": "^kubernetes-apiservers",
                "dimensions": [["ClusterName","Service"]],
                "metric_selectors": [
                 "^apiserver_request_total$"
                 ]
                },
                {"source_labels": ["job","qmgr"],
                "label_matcher": "^ibm-mq;SECUREQM$",
                "dimensions": [["ClusterName","qmgr"]],
                "metric_selectors": [
                 "^ibmmq_qmgr"
                 ]
                },
                {"source_labels": ["job","qmgr"],
                "label_matcher": "^ibm-mq-extended;SECUREQM$",
                "dimensions": [["ClusterName","qmgr","queue"]],
                "metric_selectors": [
                 "^ibmmq_queue_depth$"
                 ]
                }        
              ]
            }
          }
        },
        "force_flush_interval": 5
      }
    }
